#DataSource Configuration
spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_plan_test
    username: root
    password: admin

#  spring:
#    h2.console.enabled: true
#    h2.console.path: /h2-console
#    datasource.url: jdbc:h2:mem:project_plan
#    datasource.username: sa
#    datasource.password :
#    datasource.driver-class-name: org.h2.Driver
#    datasource.type: com.zaxxer.hikari.HikariDataSource
#    datasource.hikari.maximum-pool-size: 5
#    datasource.hikari.minimum-idle: 1
#    jpa.defer-datasource-initialization: true
#    jpa.database-platform: org.hibernate.dialect.H2Dialect
#    graphql.graphiql.enabled: true


# JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: true
      dialect = org.hibernate.dialect.MySQL5Dialect


server:
  port: 8000